log_level = 'OFF'

port = 8080

dir = '/tmp/test'

title = ''

announcement = '''
公告
欢迎
'''

[[data_nodes]]
name = 'Server-1'
[data_nodes.address]
protocol = 'http'
host = '127.0.0.1'
port = 8080

[[data_nodes]]
name = 'Server-2'
[data_nodes.address]
protocol = 'http'
host = '127.0.0.1'
port = 8082
